[package]
name = "stc_rust"
version = "0.1.0"
edition = "2024"

[lib]
name = "stc_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module", "serde"] }
serde_json = "1"